- name: DEBUG registrator command
  debug: msg="connecting to consul uri consul://{{ansible_default_ipv4.address}}:8500"

- name: Run Registrator
  docker:
    name: registrator
    image: gliderlabs/registrator:latest
    net: host
    command: consul://{{ansible_default_ipv4.address}}:8500
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    pull: always
    state: reloaded
    restart_policy: always
